### ISSUE TITLE
What encoding?

### ISSUE THREAD

**Issue by Jakobud** [bagelbits/5e-srd-api#7]
I see a lot of weird encoding characters like this: `spellâ€™s`. Should just be `spell's`.

How do we deal with this in the API?

**Comment by Jakobud** [comment]
Any word on this? Seems like a super obvious issue...

**Comment by Vice93** [comment]
Just tossing out ideas. My native encoding is UTF-8, and I receive no weird formatted responses. Did you try to convert it? Maybe try something like [https://stackoverflow.com/a/5396742/5309584](t
his)

**Comment by Jakobud** [comment]
The API website itself shows the odd characters:

![screenshot_29](https://user-images.githubusercontent.com/87356/47340661-2d4a9d00-d65c-11e8-8699-7781fa52b36a.png)

**Comment by Vice93** [comment]
No you're right. I just didn't look enough. The database .json documents themselves are saved using the wrong encoding ([CP-1252 probably](https://stackoverflow.com/a/2477480/5309584)). 

https://github.com/adrpadua/5e-database/blob/master/5e-SRD-Spells.json:
Index 1: "material": "Powdered rhubarb leaf and an adderâ€™s stomach."

However some files are saved correctly, though they're using [U-2019](http://www.fileformat.info/info/unicode/char/2019/index.htm) instead of [U+0027](https://www.fileformat.info/info/unicode/char/27/index.htm):
![image](https://user-images.githubusercontent.com/14312576/47376962-4b63dc00-d6f4-11e8-8613-8e49ccafaf1d.png)

So the fix for this is to save the wrong documents in the correct encoding (probably UTF-8).

**Comment by Vice93** [comment]
This probably happened in a pull request editing the information on a few documents. Someone should probably edit all of them and make sure they're saved correctly, and maybe replace all ´ with '.

**Comment by Jakobud** [comment]
Yeah it's not just single quote characters that are the problem. A lot of different other characters like em-dashes, etc. Looks like someone has fixed it in a commit:

https://github.com/adrpadua/5e-database/commit/11d1aaebde8debd1fe1f484b1ac4ea41b7f0489b

But I still see the bad encoding in the website. Perhaps it's just not deployed yet.

**Comment by bagelbits** [comment]
I think most of this should be cleaned up now. If you see anything else, it can be fixed here:
https://github.com/bagelbits/5e-database
